ALTER DATABASE postgres SET timezone TO 'Europe/Paris';

-- configuration_properties
DROP TABLE IF EXISTS configuration_properties;
CREATE TABLE configuration_properties (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  archiving_date TIMESTAMP NULL,
  deletable BOOLEAN NOT NULL DEFAULT true,
  read_only BOOLEAN NOT NULL DEFAULT false,
  name VARCHAR(128) NOT NULL,
  data VARCHAR(1024) DEFAULT NULL,
  creation_date TIMESTAMP NOT NULL,
  modification_date TIMESTAMP NOT NULL,
  data_type VARCHAR(48) NOT NULL,
  data_type_def VARCHAR(255) DEFAULT NULL,
  application VARCHAR(128) DEFAULT NULL,
  scope VARCHAR(128) DEFAULT NULL,
  label VARCHAR(128) DEFAULT NULL,
  mini FLOAT8 DEFAULT NULL,
  maxi FLOAT8 DEFAULT NULL,
  default_data VARCHAR(1024) DEFAULT NULL,
  CONSTRAINT unq_configuration_properties UNIQUE (name,application,scope)
);

CREATE INDEX idx_configuration_properties_application ON configuration_properties (application);
CREATE INDEX idx_configuration_properties_archiving_date ON configuration_properties (archiving_date);
CREATE INDEX idx_configuration_properties_deletable ON configuration_properties (deletable);
CREATE INDEX idx_configuration_properties_readonly ON configuration_properties (read_only);
CREATE INDEX idx_configuration_properties_name ON configuration_properties (name);
CREATE INDEX idx_configuration_properties_type ON configuration_properties (data_type);
CREATE INDEX idx_configuration_properties_scope ON configuration_properties (scope);
