spring.config.import=optional:configserver:http://${configuration_server_host:localhost}:${configuration_server_port:8888}
spring.profiles.active=${registry_service_profile:production}
spring.application.name=registry-service
server.port=${registry_service_port:8761}
eureka.instance.hostname=${registry_service_host:localhost}
eureka.instance.preferIpAddress=true
eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
eureka.renewalPercentThreshold=0.85
