spring:
  config:
    import: optional:configserver:http://${configuration_server.host:localhost}:${configuration_server.port:8888}
  profiles:
    active: actuator,${gateway_service.profile:production}
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
   port: ${gateway_service.port:8080}
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
info:
  application:
    name: ${spring.application.name}
    description: Gateway service
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
eureka:
  name: gateway-service
  client:
    serviceUrl:
      defaultZone: http://${registry_service.host:localhost}:${registry_service.port:8761}/eureka
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true  
  instance:
    prefer-ip-address: true
    ip-address: ${gateway_service.host:localhost}
    instance-id: ${gateway_service.host:localhost}:${gateway_service.port:8080}