spring.config.import=optional:configserver:http://${configuration_server_host:localhost}:${configuration_server_port:8888}
server.port=${authentication_service_port:8762}
spring.profiles.active=${authentication_service_profile:production}
spring.application.name=authentication-service
eureka.client.serviceUrl.defaultZone=http://${registry_service_host:localhost}:${registry_service_port:8761}/eureka
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.healthcheck.enabled=true  